import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import announcementsRouter from "./announcements";
import eventsRouter from "./events";
import enrollmentRouter from "./enrollment";
import galleryRouter from "./gallery";
import faqsRouter from "./faqs";
import chatRouter from "./chat";
import dashboardRouter from "./dashboard";
const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(announcementsRouter);
router.use(eventsRouter);
router.use(enrollmentRouter);
router.use(galleryRouter);
router.use(faqsRouter);
router.use(chatRouter);
router.use(dashboardRouter);
export default router;
